server:
  host: "0.0.0.0"
  port: 8080
  uri: "http://127.0.0.1:8080"

mongodb:
  uri: "mongodb://127.0.0.1:27017"
  database: "m3m"

jwt:
  expiration: 168h

storage:
  path: "/app/data/storage"

runtime:
  worker_pool_size: 50
  timeout: 30s

plugins:
  path: "/app/plugins"

logging:
  level: "info"
  path: "/app/data/logs"
